name: daily_pics
description: A new Flutter application.
version: 3.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_ionicons:
    git:
      url: https://github.com/KagurazakaHanabi/flutter_ionicons.git
  cached_network_image: ^1.0.0
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  http: ^0.12.0+2
  image_picker: ^0.6.0+15
  json_annotation: ^2.4.0
  palette_generator: ^0.1.1
  path_provider: ^1.1.0
  qr: ^1.2.0
  shared_preferences: ^0.5.3+2
  uni_links: ^0.2.0

dev_dependencies:
  build_runner: ^1.6.1
  json_serializable: ^3.0.0

flutter:
  uses-material-design: false
  assets:
    - res/
