name: daily_pics
description: A new Flutter application.
version: 3.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_ionicons:
    git:
      url: https://github.com/KagurazakaHanabi/flutter_ionicons.git
  cached_network_image: ^1.0.0
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  json_annotation: ^2.4.0
  path_provider: ^1.1.0
  qr: 1.1.1

dev_dependencies:
  build_runner: ^1.6.1
  json_serializable: ^3.0.0

flutter:
  uses-material-design: false
  assets:
    - res/
